variable "vpc-cidr" {
    default = "10.0.0.0/16"
    description = "VPC CIDR BLOCK"
    type = string 
  
}

variable "Public_Subnet_1" {
    default = "10.0.0.0/24"
    description = "Public_Subnet_1"
    type = string 
  
}
variable "Public_Subnet_2" {
    default = "10.0.1.0/24"
    description = "Public_Subnet_2"
    type = string 
  
}

variable "Private_Subnet_1" {
    default = "10.0.2.0/24"
    description = "Private_Subnet_1"
    type = string 
  
}

variable "Private_Subnet_2" {
    default = "10.0.3.0/24"
    description = "Private_Subnet_2"
    type = string 
  
}

variable "Private_Subnet_3" {
    default = "10.0.4.0/24"
    description = "Private_Subnet_3"
    type = string 
  
}

variable "Private_Subnet_4" {
    default = "10.0.5.0/24"
    description = "Private_Subnet_5"
    type = string 
  
}

variable "ssh-location" {
    default = "0.0.0.0/0"
    description = "SSH variable for bastion host"
    type = string 
  
}

variable "SSL-certificate" {
    default = "arn:aws:acm:eu-central-1:027619007323:certificate/0283ba8d-d3bf-4d94-9642-0d663f8f54ad"
    description = "SSL-certificate"
    type = string 
  
}

variable "route53_hosted_zone_name" {
    default = "awsclouddemo.tk"
    description = "domain name"
    type = string 
  
}
variable "generated_key_name" {
  type        = string
  default     = "terraform-key-pair"
  description = "Key-pair generated by Terraform"
}


variable "region" {
  type        = string
  default     = "eu-central-1"
  
}


variable "instance_type" {
  type        = string
  default     = "t2.micro"
  
}

variable "s3_bucket_name" {
  type        = string
  default     = "coffee-shop-demo-4"
  
}